name: keygen
description: RSA key generator library for MeshNote
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.6

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  elliptic: ^0.3.10
  ecdsa: ^0.1.0
  crypto: ^3.0.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
